#############################################################################
# Makefile for building: FollowOrderPro
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Aug 20 08:08:48 2018
# Project:  ../FollowOrderPro/FollowOrderPro.pro
# Template: app
# Command: /home/tff/Desktop/qt-everywhere-opensource-src-4.8.6/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.6/mkspecs/linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../FollowOrderPro/FollowOrderPro.pro
#############################################################################

####### Compiler, tools and options

CXX           = g++
CXXFLAGS      = -m64  -std=c++11  -w -O0
#INCPATH       =  -I../FollowOrderPro -I../boost_1_61_0 -I../glog_0_3_3  -I../FollowOrderPro -I. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
INCPATH       =  -I../FollowOrderPro -I../boost_1_61_0 -I../glog_0_3_3  -I../FollowOrderPro -I. 
LINK          = g++
#LFLAGS        = -m64 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.6/lib
LIBS          =    -L./lib -L../boost_1_61_0/stage/lib -L../glog_0_3_3 -lmduserapi -ltraderapi  -lboost_locale -ldl -lboost_date_time -lboost_system -lboost_thread -lpthread -lboost_chrono -lthostmduserapi -lglog -lthosttraderapi 

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../FollowOrderPro/main.cpp \
		../FollowOrderPro/DataProcessor.cpp \
		../FollowOrderPro/MdSpi.cpp \
		../FollowOrderPro/property.cpp \
		../FollowOrderPro/TraderSpi.cpp \
		../FollowOrderPro/TimeProcesser.cpp \
		../FollowOrderPro/CSHFETraderSpi.cpp 
OBJECTS       = main.o \
		DataProcessor.o \
		MdSpi.o \
		property.o \
		TraderSpi.o \
		TimeProcesser.o \
		CSHFETraderSpi.o
QMAKE_TARGET  = FollowOrderPro
DESTDIR       = 
TARGET        = FollowOrderPro

####### Build rules


$(TARGET):  $(OBJECTS)  
	$(LINK)  -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)


####### Compile

main.o: ../FollowOrderPro/main.cpp ../FollowOrderPro/DataProcessor.h \
		../FollowOrderPro/lib/ThostFtdcTraderApi.h \
		../FollowOrderPro/lib/ThostFtdcUserApiStruct.h \
		../FollowOrderPro/lib/ThostFtdcUserApiDataType.h \
		../FollowOrderPro/TraderSpi.h \
		../FollowOrderPro/property.h \
		../FollowOrderPro/TimeProcesser.h \
		../FollowOrderPro/cshfe/FtdcTraderApi.h \
		../FollowOrderPro/cshfe/FtdcUserApiStruct.h \
		../FollowOrderPro/cshfe/FtdcUserApiDataType.h \
		../FollowOrderPro/CSHFETraderSpi.h \
		../FollowOrderPro/NetSniffer.cpp \
		../FollowOrderPro/MdSpi.h \
		../FollowOrderPro/lib/ThostFtdcMdApi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../FollowOrderPro/main.cpp

DataProcessor.o: ../FollowOrderPro/DataProcessor.cpp ../FollowOrderPro/DataProcessor.h \
		../FollowOrderPro/lib/ThostFtdcTraderApi.h \
		../FollowOrderPro/lib/ThostFtdcUserApiStruct.h \
		../FollowOrderPro/lib/ThostFtdcUserApiDataType.h \
		../FollowOrderPro/TraderSpi.h \
		../FollowOrderPro/property.h \
		../FollowOrderPro/TimeProcesser.h \
		../FollowOrderPro/cshfe/FtdcTraderApi.h \
		../FollowOrderPro/cshfe/FtdcUserApiStruct.h \
		../FollowOrderPro/cshfe/FtdcUserApiDataType.h \
		../FollowOrderPro/CSHFETraderSpi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataProcessor.o ../FollowOrderPro/DataProcessor.cpp

MdSpi.o: ../FollowOrderPro/MdSpi.cpp ../FollowOrderPro/MdSpi.h \
		../FollowOrderPro/lib/ThostFtdcMdApi.h \
		../FollowOrderPro/lib/ThostFtdcUserApiStruct.h \
		../FollowOrderPro/lib/ThostFtdcUserApiDataType.h \
		../FollowOrderPro/lib/ThostFtdcTraderApi.h \
		../FollowOrderPro/TraderSpi.h \
		../FollowOrderPro/property.h \
		../FollowOrderPro/DataProcessor.h \
		../FollowOrderPro/TimeProcesser.h \
		../FollowOrderPro/cshfe/FtdcTraderApi.h \
		../FollowOrderPro/cshfe/FtdcUserApiStruct.h \
		../FollowOrderPro/cshfe/FtdcUserApiDataType.h \
		../FollowOrderPro/CSHFETraderSpi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MdSpi.o ../FollowOrderPro/MdSpi.cpp

property.o: ../FollowOrderPro/property.cpp ../FollowOrderPro/property.h \
		../FollowOrderPro/lib/ThostFtdcTraderApi.h \
		../FollowOrderPro/lib/ThostFtdcUserApiStruct.h \
		../FollowOrderPro/lib/ThostFtdcUserApiDataType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o property.o ../FollowOrderPro/property.cpp

TraderSpi.o: ../FollowOrderPro/TraderSpi.cpp ../FollowOrderPro/lib/ThostFtdcTraderApi.h \
		../FollowOrderPro/lib/ThostFtdcUserApiStruct.h \
		../FollowOrderPro/lib/ThostFtdcUserApiDataType.h \
		../FollowOrderPro/TraderSpi.h \
		../FollowOrderPro/property.h \
		../FollowOrderPro/DataProcessor.h \
		../FollowOrderPro/TimeProcesser.h \
		../FollowOrderPro/cshfe/FtdcTraderApi.h \
		../FollowOrderPro/cshfe/FtdcUserApiStruct.h \
		../FollowOrderPro/cshfe/FtdcUserApiDataType.h \
		../FollowOrderPro/CSHFETraderSpi.h \
		../FollowOrderPro/TradeProcessor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TraderSpi.o ../FollowOrderPro/TraderSpi.cpp

TimeProcesser.o: ../FollowOrderPro/TimeProcesser.cpp ../FollowOrderPro/TimeProcesser.h \
		../FollowOrderPro/property.h \
		../FollowOrderPro/lib/ThostFtdcTraderApi.h \
		../FollowOrderPro/lib/ThostFtdcUserApiStruct.h \
		../FollowOrderPro/lib/ThostFtdcUserApiDataType.h \
		../FollowOrderPro/DataProcessor.h \
		../FollowOrderPro/TraderSpi.h \
		../FollowOrderPro/cshfe/FtdcTraderApi.h \
		../FollowOrderPro/cshfe/FtdcUserApiStruct.h \
		../FollowOrderPro/cshfe/FtdcUserApiDataType.h \
		../FollowOrderPro/CSHFETraderSpi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TimeProcesser.o ../FollowOrderPro/TimeProcesser.cpp

CSHFETraderSpi.o: ../FollowOrderPro/CSHFETraderSpi.cpp ../FollowOrderPro/CSHFETraderSpi.h \
		../FollowOrderPro/cshfe/FtdcTraderApi.h \
		../FollowOrderPro/cshfe/FtdcUserApiStruct.h \
		../FollowOrderPro/cshfe/FtdcUserApiDataType.h \
		../FollowOrderPro/DataProcessor.h \
		../FollowOrderPro/lib/ThostFtdcTraderApi.h \
		../FollowOrderPro/lib/ThostFtdcUserApiStruct.h \
		../FollowOrderPro/lib/ThostFtdcUserApiDataType.h \
		../FollowOrderPro/TraderSpi.h \
		../FollowOrderPro/property.h \
		../FollowOrderPro/TimeProcesser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CSHFETraderSpi.o ../FollowOrderPro/CSHFETraderSpi.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

clean:
	rm -rf $(OBJECTS) FollowOrderPro
